#!/usr/bin/env Rscript
library(uwot)
library(ggplot2)
library(gridExtra)

# Read data generated by Rust
data <- as.matrix(read.csv("bench_data.csv", header = FALSE))
labels <- read.csv("bench_labels.csv")$cluster
rust_emb <- read.csv("bench_rust_embedding.csv")

cat(sprintf("Dataset: %d samples, %d features, %d clusters\n",
            nrow(data), ncol(data), length(unique(labels))))

# Run uwot
set.seed(42)
uwot_emb <- umap(data, n_neighbors = 15, n_components = 2, min_dist = 0.1,
                  n_epochs = 200, verbose = FALSE)
uwot_emb <- data.frame(V1 = uwot_emb[, 1], V2 = uwot_emb[, 2])

# Compute separation metrics
calc_sep <- function(emb, labs, name) {
  within_d <- c()
  between_d <- c()
  n <- nrow(emb)
  # Sample pairs to avoid O(n^2) for large n
  set.seed(1)
  n_pairs <- min(50000, n * (n - 1) / 2)
  for (p in 1:n_pairs) {
    i <- sample(n, 1)
    j <- sample(n, 1)
    if (i == j) next
    d <- sqrt((emb$V1[i] - emb$V1[j])^2 + (emb$V2[i] - emb$V2[j])^2)
    if (labs[i] == labs[j]) {
      within_d <- c(within_d, d)
    } else {
      between_d <- c(between_d, d)
    }
  }
  sep <- mean(between_d) / mean(within_d)
  cat(sprintf("\n%s:\n", name))
  cat(sprintf("  Avg within-cluster distance:  %.3f\n", mean(within_d)))
  cat(sprintf("  Avg between-cluster distance: %.3f\n", mean(between_d)))
  cat(sprintf("  Separation ratio:             %.3f\n", sep))
  cat(sprintf("  Std X: %.3f\n", sd(emb$V1)))
  cat(sprintf("  Std Y: %.3f\n", sd(emb$V2)))
  return(sep)
}

rust_sep <- calc_sep(rust_emb, labels, "Rust UMAP (TurboQuant + HNSW)")
uwot_sep <- calc_sep(uwot_emb, labels, "R uwot")

cat(sprintf("\nQuality ratio: %.1f%%\n", 100 * rust_sep / uwot_sep))

# Visualize
make_plot <- function(emb, title) {
  df <- data.frame(x = emb$V1, y = emb$V2, cluster = factor(labels))
  ggplot(df, aes(x = x, y = y, color = cluster)) +
    geom_point(size = 1.2, alpha = 0.6) +
    scale_color_manual(values = c("#E69F00", "#56B4E9", "#009E73", "#CC79A7")) +
    labs(title = title, x = "UMAP 1", y = "UMAP 2") +
    theme_minimal() +
    theme(legend.position = "bottom",
          plot.title = element_text(hjust = 0.5, face = "bold", size = 13))
}

p1 <- make_plot(rust_emb, "Rust UMAP\n(TurboQuant + HNSW)")
p2 <- make_plot(uwot_emb, "R uwot UMAP")

png("compare_quality.png", width = 1200, height = 600, res = 120)
grid.arrange(p1, p2, ncol = 2)
dev.off()

cat("\nSaved: compare_quality.png\n")
